# What Python version is installed where:
# http://www.appveyor.com/docs/installed-software#python

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      TOX_ENV: "py27"

    - PYTHON: "C:\\Python36"
      TOX_ENV: "py36"

install:
  - "%PYTHON%/Scripts/pip install tox"
  - "%PYTHON%/Scripts/pip install wheel"

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - "%PYTHON%/Scripts/tox -e %TOX_ENV%"
